[package]
name = "rpn_calculator"
version = "0.1.0"
authors = ["Thibaud ROBERT <siouxthibaud@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

